//created on: Sep 29, 2019
package com.droolscours

//#list any import classes here.
import com.droolscours.Account;
import com.droolscours.AccountingPeriod;
import com.droolscours.CashFlow;
import com.util.OutputDisplay;

global OutputDisplay showResults;

rule "start process"
    when
    then
        kcontext.getKieRuntime().startProcess("RF3");
end

rule "Account group1"
    ruleflow-group "Group1"
    when
        Account(balance > 0  )
    then 
        showResults.showText("Account in Group1 > 1000 ");

end
rule "Account group2"
    ruleflow-group "Group2"
    when
        Account(  )
    then 
        showResults.showText("Account in Group2 < 1000");

end